### ISSUE TITLE
Issue with Youtube red videos

### ISSUE THREAD

**Issue by terrisbecker** [mirror12k/python-youtube-videos-lister#1]
I think i have found an issue when trying to list videos that are uploaded for youtube red. The code runs smoothly until I reach the last channel listed on the subs.lst file (user/Vsauce). Vsauce creates videos for both YouTube and YouTube red and I believe the issue occurs because it is the only channel I subscribe to that creates for YouTube red. In any case, I get the following error.

Traceback (most recent call last):
  File "C:\Users\terri\Python\get_new_videos.py", line 51, in <module>
    videos = getRecent(channel, time)
  File "C:\Users\terri\Python\get_new_videos.py", line 34, in getRecent
    return [ video for video in youtube_api.channelVideos(channel+'/videos') if parseTime(video['age']) <= timeFrame ]
  File "C:\Users\terri\Python\youtube_api.py", line 19, in channelVideos
    views = videoMetaInfo.xpath('./li[1]/text()')[0]
IndexError: list index out of range

Once again I believe the issue is with videos uploaded for YouTube red because the code runs fine without the inclusion of user/Vsauce. I just don't know how to fix it.

**Comment by mirror12k** [comment]
I've looked into the issue and yes, it is related to youtube red. It seems that youtube has clobbered old data that the script was relying on. I'm currently looking into a solution.

**Comment by terrisbecker** [comment]
Great! Keep me updated. I'm using the script to get the URL of my subscriptions so I am able to work around the issue. But in the future I may want to use the rest of the data. Thanks

**Comment by mirror12k** [comment]
I have uploaded a fix to prevent it from crashing due to youtube red accounts. It can now parse some youtube red videos, unfortunately youtube refuses to send any date for videos with a season listing (ex. 'S2 E5'), and so the script ignores any videos with a season listing. I hope this alleviates your issue.

**Comment by terrisbecker** [comment]
Thank you. It works perfectly for me now.
